// priority: 10
StartupEvents.registry('item', event => {
    event.create('half_syrup').texture('dlc:organ/maple_syrup')
    event.create('half_jelly').texture('dlc:organ/jelly_muscle')
    event.create('half_lung').texture('dlc:organ/candy_lung')
    event.create('half_ginger_man').texture('dlc:organ/ginger_man')
    event.create('half_rib').texture('dlc:organ/candy_rib')
    event.create('half_kidney').texture('dlc:organ/candy_kidney')
    event.create('half_temperature_controller').texture('dlc:organ/temperature_controller')
    event.create('half_recycle_system').texture('dlc:organ/recycle_system')
    event.create('half_machine_core').texture('dlc:organ/machine_core')
    event.create('blank_bamboo_slip').texture('dlc:item/blank_bamboo_slip').displayName('空白竹简')
    event.create('bamboo_slip').texture('dlc:item/bamboo_slip').displayName('竹简')
    event.create('moonlight_staff','irons_spells_js:magic_sword')
    .displayName('月光大杖')
    .addDefaultSpell(SpellRegistry.STARFALL_SPELL,70)
    .tooltip(Text.of('想做你的傀儡，在你的指尖起舞').color('#fffbd0'))
    .texture('dlc:item/moonlight_staff')
    .addAdditionalAttribute('irons_spellbooks:spell_power', 'moonlightStaffSpellPower', 5, 'addition')
    .addAdditionalAttribute('irons_spellbooks:max_mana', 'moonlightStaffMana', 1000, 'addition')
    .addAdditionalAttribute('irons_spellbooks:mana_regen','moonlightStaffManaRegen',1,'addition')
    .addAdditionalAttribute('irons_spellbooks:cooldown_reduction','moonlightStaffCooldown',0.5,'addition')
    .attackDamageBaseline(8.0)
    .attackDamageBonus(3)
    .speedBaseline(-1)
    .speed(4.0)
    .maxDamage(2333)
    .rarity('epic')
});