// priority: 1
StartupEvents.registry('item', event => {
    /**
     * 
     * @param {Organ} organ 
     * @returns {Internal.BasicItemJS$Builder}
     */
    function registerOrgan(organ) {
        global.ORGAN_LIST.push(organ)
        let builder = event.create(organ.itemID).maxStackSize(organ.maxStackSize).tag('kubejs:organ').group("kubejs.dlc")
        if (organ.ctrlTextLines.length > 0) {
            builder.tag('chestcavity:active')
        }
        if (organ.altTextLines.length > 0) {
            builder.tag('chestcavity:special')
        }
        return builder
    }

    /**
     * 
     * @param {Organ} organ 
     */
    global.ORGAN_LIST.forEach(organ=>{
        if(organ.itemID==='kubejs:candy_heart')
        {
            while (organ.organScores.pop() != undefined);
            while (organ.shiftTextLines.pop() != undefined);
            organ
            .addScore('nutrition', 1.5)
            .addScore('sweetness',20)
            .addScore('health',5)
            .build();
        }
        else if(organ.itemID==='kubejs:candy_stomach')
        {
            while (organ.organScores.pop() != undefined);
            while (organ.shiftTextLines.pop() != undefined);
            organ
            .addScore('nutrition', 1.5)
            .addScore('digestion', 2)
            .addScore('sweetness',15).build();
        }
        else if(organ.itemID==='kubejs:candy_pancreas')
        {
            while (organ.organScores.pop() != undefined);
            while (organ.shiftTextLines.pop() != undefined);
            organ
            .addScore('endurance', 2.5)
            .addScore('health', 0.5)
            .addScore('sweetness',10).build();
        }
        else if(organ.itemID==='kubejs:color_palette')
        {
            while(organ.altTextLines.pop()!=undefined);
            organ
            .addTextLines('alt', [LEADING_SYMBOL, Text.gray('手持'),Text.gold('大艺术家法杖'),Text.gray('造成法术伤害时，如果法术为：')])
            .addTextLines('alt', [LEADING_SYMBOL, Text.green('毒箭射击'),Text.gray('、'),Text.gold('火焰箭'),Text.gray('、'),Text.blue('冰锥'),Text.gray('、'),Text.darkRed('猩红之刺（猩红刺狱）'),Text.gray('、'),Text.of('荆棘之梦').color('#e8a0dc'),Text.gray('、'),Text.darkPurple('魔法箭')])
            .addTextLines('alt', [LEADING_SYMBOL, Text.gray('会造成'),Text.gold('当前法力值/30（色彩状态下为min(28-色彩效果等级,20))'),Text.gray('的额外伤害')])
        }
    });




    registerOrgan(new Organ('kubejs:candy_lung')
        .addScore('burning_point', -5)
        .addScore('health', -0.25)
        .addScore('breath_recovery', 0.5)
        .addScore('nutrition',0.5)
        .addScore('sweetness', 4)
        .addTextLines('default', [Text.gray('空气也变得甜蜜')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('吸收20%伤害(此效果唯一)')])
        .build())
        .texture('dlc:organ/candy_lung')
        .tag('kubejs:lung')
        .tag('kubejs:candy')
        .tag('kubejs:food')
        .food(food => {food.hunger(4).saturation(3).alwaysEdible()})
        .displayName('棉花糖肺');

    registerOrgan(new Organ('kubejs:ginger_man_totem')
        .addScore('health', -0.25)
        .addScore('breath_recovery', 1.5)
        .addScore('nutrition',0.5)
        .addScore('sweetness', 2)
        .addTextLines('default', [Text.gray('刀剑劈开的，并非身躯')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('在糖果器官种类大于等于4时，可以抵挡一次致命攻击\n根据糖果器官的种类及数量提供一次糖果之梦效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('冷却为25s')])
        .build())
        .texture('dlc:organ/ginger_man')
        .tag('kubejs:candy')
        .tag('kubejs:food')
        .food(food => {food.hunger(6).saturation(2.5).alwaysEdible()})
        .displayName('姜饼人替身');
    
    registerOrgan(new Organ('kubejs:jelly_muscle')
        .addScore('burning_point', -1)
        .addScore('strength', 1.0)
        .addScore('speed',1.0)
        .addScore('knockback_resistant', 1.5)
        .addScore('impact_resistant', 1.5)
        .addScore('nutrition',0.5)
        .addScore('safe_fall_distance',8)
        .addScore('sweetness', 1)
        .addTextLines('default', [Text.gray('弹弹的')])
        .build())
        .texture('dlc:organ/jelly_muscle')
        .tag('kubejs:muscle')
        .tag('kubejs:candy')
        .tag('kubejs:food')
        .food(food => {food.hunger(3).saturation(1).alwaysEdible()})
        .displayName('果冻肌肉');

    registerOrgan(new Organ('kubejs:maple_syrup')  //记得修改数量计算方式
        .addScore('health', 0.4)
        .addScore('nerves', 0.4)
        .addScore('breath_recovery', 0.4)
        .addScore('strength', 0.4)
        .addScore('filtration', 0.4)
        .addScore('detoxification', 0.4)
        .addScore('defense', 0.2)
        .addScore('nutrition', 0.2)
        .addScore('endurance', 0.4)
        .addScore('digestion', 0.2)
        .addScore('metabolism', 0.4)
        .addScore('breath_capacity', 0.4)
        .addScore('speed', 0.4)
        .addScore('burning_point', -2)
        .addScore('sweetness', 1)
        .addTextLines('default', [Text.gray('魔法使的糖果心，当然流动着'),Text.of('糖').color('#e8a0dc')])
        .build())
        .texture('dlc:organ/maple_syrup')
        .tag('kubejs:candy')
        .tag('kubejs:food')
        .food(food => {food.hunger(3).saturation(2).alwaysEdible()})
        .displayName('枫糖浆');

    registerOrgan(new Organ('kubejs:candy_rib')  //记得修改数量计算方式
        .addScore('strength', 0.5)
        .addScore('defense', 1.5)
        .addScore('burning_point', -4)
        .addScore('sweetness', 4)
        .addTextLines('default', [Text.gray('以'),Text.of('糖').color('#e8a0dc'),Text.gray('克刚')])
        .build())
        .texture('dlc:organ/candy_rib')
        .tag('kubejs:candy')
        .tag('kubejs:food')
        .food(food => {food.hunger(4).saturation(1.5).alwaysEdible()})
        .displayName('橡皮糖肋骨');

    
    registerOrgan(new Organ('kubejs:candy_kidney')
        .addScore('detoxification', 1)
        .addScore('filtration', 1.5)
        .addScore('nutrition', 1)
        .addScore('sweetness', 1.5)
        .addScore('burning_point', -1)
        .addTextLines('default', [Text.gray('你前所未有的清醒')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('拥有糖果器官种类大于等于5时，提供糖果冲刺效果')])
        .build())
        .texture('dlc:organ/candy_kidney')
        .tag('kubejs:kidney')
        .tag('kubejs:candy')
        .tag('kubejs:food')
        .tag('kubejs:player_tick_only')
        .food(food => {food.hunger(2).saturation(1).alwaysEdible()})
        .displayName('冰糖肾脏');
    
    registerOrgan(new Organ('kubejs:sculk_core')
        .addScore('health', 3.0)
        .addScore('endurance', 3.0)
        .addScore('nerves', 2.0)
        .addTextLines('default', [Text.gray('它听见了')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('使用主动按键可在对应方向连续唤起3次监守者音爆，玩家经验等级及幽匿器官数量给予额外伤害加成')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('对途径的每个目标造成多段音爆伤害，对指向目标产生额外伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('冷却30s，该音爆每击中一次敌人冷却降低3s')])
        .build())
        .texture('dlc:organ/sculk_core')
        .tag('kubejs:heart')
        .tag('kubejs:sculk')
        .tag('kubejs:key_pressed')
        .displayName('幽匿核心');

    registerOrgan(new Organ('kubejs:sculk_eye')
        .addScore('nerves', 8.0)
        .addTextLines('default', [Text.gray('即使已经退化，它仍想念地上的风景')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('获得夜视效果，并不再受黑暗效果影响')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('存在幽匿核心时，根据音爆击中的敌人数量给予玩家深渊庇佑效果以及数值提升')])
        .build())
        .texture('dlc:organ/sculk_eye')
        .tag('kubejs:player_effect_only')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:heart')
        .tag('kubejs:sculk')
        .displayName('幽匿之眼');

    registerOrgan(new Organ('kubejs:sculk_lamp')
        .addScore('nerves', 5.0)
        .addScore('speed', 1.5)
        .addTextLines('default', [Text.gray('它已经燃烧了很久...')])
        .addTextLines('default', [Text.of('也会继续燃烧下去').color('#0b616b')])
        .build())
        .texture('dlc:organ/sculk_lamp')
        .tag('kubejs:relics')
        .tag('kubejs:sculk')
        .displayName('幽匿魂盏');

    registerOrgan(new Organ('kubejs:temperature_controller')
        .addScore('strength', 1.5)
        .addScore('filtration', 1.5)
        .addTextLines('default', [Text.gray('恒温系统！')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('当体温高于50度时，提供额外的心火/融火效果，并将体温保持在50度')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('该器官提供的心火/融火效果等级不会超过100')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('安装该器官后，心火/融火效果时间不会超过1200s')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('当体温低于-50度时，提供额外的法强，并将体温保持在-50度')])
        .build())
        .texture('dlc:organ/temperature_controller')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:flame')
        .tag('kubejs:ice')
        .tag('kubejs:machine')
        .displayName('温度控制系统');

    registerOrgan(new Organ('kubejs:gold_cup')
        .addScore('strength', 4.0)
        .addScore('health', 1.0)
        .addTextLines('default', [Text.gray('财富，象征着权力')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后，根据资源点数上限及资源点数提供基础数值加成')])
        .build())
        .texture('dlc:organ/gold_cup')
        .tag('kubejs:active_only')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:resource')
        .displayName('金酒之杯');
    
    registerOrgan(new Organ('kubejs:recycle_system')
        .addScore('strength', -0.5)
        .addScore('health', -1.5)
        .addScore('filtration', 4.0)
        .addTextLines('default', [Text.gray('高效')])
        .addTextLines('ctrl',[LEADING_SYMBOL, Text.gray('激活后根据体内资源器官数量增加资源点数上限')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('每杀死一个生物，获得5资源点数')])
        .build())
        .texture('dlc:organ/recycle_system')
        .tag('kubejs:loot_entity')
        .tag('kubejs:active')
        .tag('kubejs:machine')
        .tag('kubejs:resource')
        .displayName('残骸回收系统');

    registerOrgan(new Organ('kubejs:carry_crayon')
        .addScore('strength', 1.5)
        .addScore('speed', 0.5)
        .addTextLines('default', [Text.gray('不掉色...吧？')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('提供额外色彩效果等级')])
        .build())
        .texture('dlc:organ/carry_crayon')
        .tag('kubejs:magic')
        .tag('kubejs:color')
        .displayName('随身蜡笔');

    registerOrgan(new Organ('kubejs:pigment_bubble')
        .addScore('breath_recovery', -1.0)
        .addScore('speed', -0.5)
        .addTextLines('default', [Text.gray('颜料泡泡，发射吧！')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('按下主动技能按键，为半径30格所有生物添加颜料束缚效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('使生物行动缓慢且易伤，并取消生物无敌时间')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('提供额外色彩效果等级')])
        .build())
        .texture('dlc:organ/pigment_bubble')
        .tag('kubejs:key_pressed')
        .tag('kubejs:magic')
        .tag('kubejs:color')
        .displayName('颜料泡泡');

    registerOrgan(new Organ('kubejs:spirits_bone')
        .addScore('defense', 8)
        .addTextLines('default', [Text.gray('魔力锻体')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后根据魔力上限提供基础数值')])
        .build())
        .texture('dlc:organ/spirits_bone')
        .tag('kubejs:active_only')
        .tag('kubejs:color')
        .tag('kubejs:magic')
        .displayName('束灵骨');

    registerOrgan(new Organ('kubejs:disaster_source')
        .addScore('defense', -8)
        .addTextLines('default', [Text.gray('共赴灭亡')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('累计所受伤害，并根据所受伤害提高攻击力')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('在20秒不受伤害或累计值大于200后受到下一次伤害时，或登出时')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('会重置累计值并对玩家和直接攻击者造成1次伤害值等于累计值*20的伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('如果没有直接攻击者，则将该伤害平分给玩家附近8格的生物（包括玩家）')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('每次重生或进入游戏会重置累计值')])
        .build())
        .tag('kubejs:chaos')
        .texture('dlc:organ/disaster_source')
        .displayName('灾难之源');

    registerOrgan(new Organ('kubejs:machine_core')
        .addScore('health', 3)
        .addTextLines('default', [Text.gray('资源，火焰与机器')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后增加200点资源上限')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('根据当前资源点数获得心火/熔火效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('根据每秒资源点数变化量提供基础数值加成')])
        .build())
        .texture('dlc:organ/machine_core')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:active_only')
        .tag('kubejs:machine')
        .tag('kubejs:resource')
        .displayName('机械核心');
    
    registerOrgan(new Organ('kubejs:jingmai')  //记得修改数量计算方式
        .addScore('health', 0.4)
        .addScore('nerves', 0.6)
        .addScore('breath_recovery', 0.4)
        .addScore('strength', 0.4)
        .addScore('filtration', 0.4)
        .addScore('detoxification', 0.4)
        .addScore('defense', 0.2)
        .addScore('nutrition', 0.2)
        .addScore('endurance', 0.4)
        .addScore('digestion', 0.2)
        .addScore('metabolism', 0.4)
        .addScore('breath_capacity', 0.4)
        .addScore('speed', 0.4)
        .addScore('burning_point', 1)
        .addScore('qi_max', 2)
        .addTextLines('default', [Text.gray('内属于腑脏，外络于肢节')])
        .build())
        .texture('dlc:organ/jingmai')
        .tag('kubejs:cultivate')
        .displayName('经脉');

    registerOrgan(new Organ('kubejs:dantian_up')
        .addScore('health', 2.0)
        .addScore('strength', 2.0)
        .addScore('nerves', 6.0)
        .addScore('qi_max', 10)
        .addTextLines('default', [Text.gray('藏神之府')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('气的上限提升至2.5倍,恢复速度增加(此效果唯一)')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('内丹的前置器官')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('缓慢在体内生成经脉')])
        .build())
        .texture('dlc:organ/dantian_up')
        .tag('kubejs:cultivate')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:heart')
        .displayName('上丹田');

    registerOrgan(new Organ('kubejs:dantian_middle')
        .addScore('health', 6.0)
        .addScore('strength', 2.0)
        .addScore('nerves', 2.0)
        .addScore('qi_max', 20)
        .addTextLines('default', [Text.gray('藏气之府')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('气的上限提升至2.5倍,恢复速度增加(此效果唯一)')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('内丹的前置器官')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('缓慢在体内生成经脉')])
        .build())
        .texture('dlc:organ/dantian_middle')
        .tag('kubejs:cultivate')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:heart')
        .displayName('中丹田');

    registerOrgan(new Organ('kubejs:dantian_down')
        .addScore('health', 2.0)
        .addScore('strength',6.0)
        .addScore('nerves', 2.0)
        .addScore('qi_max', 10)
        .addTextLines('default', [Text.gray('藏精之府')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('气的上限提升至2.5倍,恢复速度增加(此效果唯一)')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('内丹的前置器官')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('缓慢在体内生成经脉')])
        .build())
        .texture('dlc:organ/dantian_down')
        .tag('kubejs:cultivate')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:heart')
        .displayName('下丹田');

    registerOrgan(new Organ('kubejs:yuanshen')
        .addScore('health', 12.0)
        .addScore('nerves', 9.0)
        .addScore('strength', 6.0)
        .addScore('qi_max', 25)
        .addTextLines('default', [Text.gray('内念不萌，外想不入，独我自主')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('气的上限提升至4倍且恢复速度大幅提升，法术强度提升至2倍(此效果唯一)')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('释放法术时花费等于法术消耗5倍的气对法术进行升级或超限')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('提升等级等于floor(气上限/8000)')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('持续积累[悟道]')])
        .build())
        .texture('dlc:organ/yuanshen')
        .tag('kubejs:heart')
        .tag('kubejs:cultivate')
        .tag('kubejs:player_tick_only')
        .displayName('元神');

    registerOrgan(new Organ('kubejs:neidan')
        .addScore('health', 12.0)
        .addScore('nerves', 9.0)
        .addScore('strength', 6.0)
        .addScore('qi_max', 30)
        .addTextLines('default', [Text.gray('炼气化神，炼神还虚')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('根据体内修真器官数量提升法术强度，气的恢复速度增加')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('消耗气可进行飞行')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('元神的前置器官')])
        .build())
        .texture('kubejs:item/organs/alex/sunbird_crystals')
        .tag('kubejs:heart')
        .tag('kubejs:cultivate')
        .displayName('内丹');

    registerOrgan(new Organ('kubejs:tree_heart')
        .addScore('health', 10.0)
        .addScore('endurance',3.0)
        .addScore('burning_point', 7)
        .addScore('freezing_point', -7)
        .addTextLines('default', [Text.gray('蓬勃的生命迸发而出')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('释放树皮时，树皮等级+1')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('按下主动技能按键获得古树之佑效果，冷却为80s')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('每拥有一个自然器官，增加0.5自然法术伤害倍率')])
        .build())
        .texture('dlc:organ/tree_heart')
        .tag('kubejs:heart')
        //.tag('kubejs:botany')
        .tag('kubejs:active_only')
        .tag('kubejs:key_pressed')
        .tag('kubejs:nature')
        .displayName('古树之心');

    registerOrgan(new Organ('kubejs:tree_heart_template')
        .addTextLines('default', [Text.gray('在器官容器中进化')])
        .build())
        .texture('dlc:organ/tree_heart')
        .tag('kubejs:heart')
        .tag('kubejs:nature')
        .displayName('古树之心模板');
    
    registerOrgan(new Organ('kubejs:tree_leaf')
        .addScore('speed',0.5)
        .addScore('detoxification', 1.0)
        .addScore('metabolism', 1.25)
        .addScore('filtration', 1.25)
        .addScore('photosynthesis', 0.5)
        .addScore('breath_recovery', 0.5)
        .addScore('burning_point', 2)
        .addScore('freezing_point', -2)
        .addTextLines('default', [Text.gray('阳光与生机')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('存在古树之佑效果且光照等级大于等于8时，每10秒')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('根据体内自然器官的数量与玩家最大生命值提供临时生命值')])
        .build())
        .texture('dlc:organ/tree_leaf')
        .tag('kubejs:nature')
        //.tag('kubejs:botany')
        .tag('kubejs:player_tick_only')
        .displayName('古树之叶');
 
    registerOrgan(new Organ('kubejs:tree_branch')
        .addScore('speed',-0.25)
        .addScore('defense',1.75)
        .addScore('photosynthesis', 0.1)
        .addScore('burning_point', 3)
        .addScore('freezing_point', -3)
        .addTextLines('default', [Text.gray('虬结的古老树枝')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('存在古树之佑效果时')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('如果玩家处于群系的降水类型为降雨/降雪，为玩家提供力量效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('如果玩家处于群系的降水类型不为降雨/降雪，为玩家提供抗性提升效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('效果等级取决于自然器官数量，器官提供效果会覆盖其他相同效果')])
        .build())
        .texture('dlc:organ/tree_branch')
        .tag('kubejs:nature')
        //.tag('kubejs:botany')
        .tag('kubejs:player_tick_only')
        .displayName('古树枝桠');

    registerOrgan(new Organ('kubejs:tree_body')
        .addScore('speed',-3.0)
        .addScore('endurance',9.0)
        .addScore('defense',20)
        .addScore('knockback_resistant', 10)
        .addScore('impact_resistant', 10)
        .addScore('photosynthesis', 1.0)
        .addScore('burning_point', 10)
        .addScore('freezing_point', -10)
        .addTextLines('default', [Text.gray('森林的重量，令人安心')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('生命上限提升至1.5倍')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('免疫坠落伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('存在古树之佑效果时')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('受伤时有30%概率增加等同于伤害值的临时生命')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('受伤时有30%概率取消本次伤害并对敌人造成一次等量伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('两次概率分别计算')])
        .build())
        .texture('dlc:organ/tree_body')
        .tag('kubejs:nature')
        //.tag('kubejs:botany')
        .tag('kubejs:bear_only')
        .displayName('古树躯干');

    event.create('kubejs:chaos_tumor')
        .texture('kubejs:item/organs/infected/random_tumor')
        .maxStackSize(1)
        .tag('kubejs:organ')
        .displayName('混沌肿瘤')
        .texture('dlc:organ/chaos_tumor')
        .group("kubejs.dlc")
        .tag('kubejs:key_pressed')
        .tag('kubejs:player_tick')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:loot_entity')
        .tag('kubejs:loot_entity_only')
        .tag('kubejs:active_only')
        .tag('kubejs:active')
        .tag('kubejs:bear_only')
        .tag('kubejs:damage_only')
        .tag('kubejs:chaos')
        .tag('kubejs:eat_effect')
        .tag('kubejs:eat_effect_only')
        .tooltip('可融合最多3个非修真器官，继承其属性及部分特殊属性')
    
    registerOrgan(new Organ('kubejs:gravitational_iris')
        .addScore('nerves',3.0)
        .addScore('crystalsynthesis',1.0)
        .addTextLines('default', [Text.gray('旋转的星河')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('受到伤害使生命低于10%时，取消本次伤害并释放超限：黑洞')])
        .build())
        .texture('dlc:organ/gravitational_iris')
        .tag('kubejs:star')
        .tag('kubejs:bear_only')
        .displayName('引力虹膜');


    registerOrgan(new Organ('kubejs:entropy_stomach')
        .addScore('nutrition', 4.0)
        .addScore('metabolism', -1.5)
        .addScore('detoxification', -1.5)
        .addTextLines('default', [Text.gray('狂乱的鸡尾酒')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('食用食物时获得3种随机效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('效果等级为1~5，时长为10~100秒')])
        .build())
        .texture('dlc:organ/entropy_stomach')
        .tag('kubejs:chaos')
        .tag('kubejs:stomach')
        .tag('kubejs:eat_effect')
        .displayName('无序胃囊');

    registerOrgan(new Organ('kubejs:abyss_gaze')
        .addScore('health',-1.0)
        .addScore('nerves',-1.5)
        .addScore('speed',-0.5)
        .addTextLines('default', [Text.gray('归于混沌')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('对看向的目标造成随机伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('伤害值取决于混沌器官的种类和数量')])
        .build())
        .texture('dlc:organ/abyss_gaze')
        .tag('kubejs:chaos')
        .tag('kubejs:player_tick_only')
        .displayName('混沌之瞳');

    registerOrgan(new Organ('kubejs:chance_tedons')
        .addScore('speed',3.0)
        .addScore('defense',-1.0)
        .addScore('strength',1.0)
        .addTextLines('default', [Text.gray('闪烁的概率')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('造成伤害的0%~20%变为真实伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('奔跑时，每0.5秒有30%概率进行一次瞬间移动')])
        .build())
        .texture('dlc:organ/chance_tedons')
        .tag('kubejs:chaos')
        .tag('kubejs:muscle')
        .tag('kubejs:damage_only')
        .displayName('概率肌腱');
        
    registerOrgan(new Organ('kubejs:pyroclastic_scope')
        .addScore('hydroallergenic', 1.0)
        .addScore('nerves',1.5) 
        .addTextLines('default', [Text.gray('便携式矿透（？')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('使用[记录矿物类型]按键可记录主手上的方块类型')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('显示以自身为中心的33*33*17范围的相同类型方块')])
        .build())
        .texture('dlc:organ/pyroclastic_scope')
        .tag('kubejs:smelt')
        .tag('kubejs:flame')
        .displayName('狱炎视界');

    registerOrgan(new Organ('kubejs:lava_core')
        .addScore('hydroallergenic', 2.0)
        .addScore('strength',1.50)
        .addScore('burning_point', -10)
        .addScore('freezing_point', -20)
        .addTextLines('default', [Text.gray('此身即为熔炉')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('获得自动熔炼效果，挖掘方块自动熔炼')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('免疫火焰伤害')])
        .build())
        .texture('dlc:organ/lava_core')
        .tag('kubejs:smelt')
        .tag('bear_only')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:flame')
        .displayName('岩浆核心');

    registerOrgan(new Organ('kubejs:life_devouring_bone')
        .addScore('strength',2.5)
        .addScore('health',-0.5)
        .addScore('defense',-1.0)
        .addTextLines('default', [Text.gray('吞噬')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('造成伤害恢复自身5%血量')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('血量在95%以上时，攻击伤害增加自身最大血量的50%')])
        .build())
        .texture('dlc:organ/life_devouring_bone')
        .tag('kubejs:smelt')
        .tag('kubejs:damage_only')
        .displayName('噬生骨');

    registerOrgan(new Organ('kubejs:void_engine')
        .addScore('speed',2.0)
        .addScore('strength',1.5)
        .addScore('health',0.5)
        .addScore('leaping', 0.5)
        .addScore('crystalsynthesis',1.5)
        .addTextLines('default', [Text.gray('天空即为极限')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('手持含石头标签的方块右键可获得2分钟鞘翅飞行效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('鞘翅飞行自动加速')])
        .build())
        .texture('dlc:organ/void_engine')
        .tag('kubejs:star')
        .tag('kubejs:machine')
        .displayName('虚空引擎');

    registerOrgan(new Organ('kubejs:star_gallblader')
        .addScore('strength', 2)
        .addScore('leaping', 0.5)
        .addScore('crystalsynthesis',1.5)
        .addTextLines('default', [Text.gray('旋转的微型星云团')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('攻击附带10%虚空伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('免疫弹射物伤害')])
        .build())
        .texture('dlc:organ/star_gallblader')
        .tag('kubejs:star')
        .tag('kubejs:bear_only')
        .tag('kubejs:damage_only')
        .displayName('星核胆囊');

    registerOrgan(new Organ('kubejs:star_spleen')
        .addScore('metabolism', 1.5)
        .addScore('crystalsynthesis',1.5)
        .addScore('burning_point', -10)
        .addScore('freezing_point', -20)
        .addTextLines('default', [Text.gray('它只待喷发')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('攻击着火的敌人有30%概率生成微型黑洞，冷却30秒')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('攻击时有30%概率释放烈焰打击')])
        .build())
        .texture('dlc:organ/star_spleen')
        .tag('kubejs:star')
        .tag('kubejs:damage_only')
        .tag('kubejs:flame')
        .displayName('星焰脾脏');

    registerOrgan(new Organ('kubejs:spider_gland')
        .addScore('detoxification',1.5)
        .addScore('speed',-0.5)
        .addTextLines('default', [Text.gray('I\'m 失败的man')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('可以像蜘蛛一样爬墙')])
        .build())
        .texture('dlc:organ/spider_gland')
        .displayName('蜘蛛丝腺');
    
    registerOrgan(new Organ('kubejs:thunderstorm_feather')
        .addScore('nerves',1.5)
        .addScore('detoxification',1.0)
        .addTextLines('default', [Text.gray('呼风唤雨')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('按下主动技能按键将天气修改为雷暴')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后根据魔法器官数量增加雷电法术强度')])
        .build())
        .texture('dlc:organ/thunderstorm_feather')
        .tag('kubejs:active_only')
        .tag('kubejs:magic')
        .tag('kubejs:key_pressed')
        .displayName('雷鸟羽毛');

    registerOrgan(new Organ('kubejs:stellar_pathway')
        .addScore('crystalsynthesis',0.5)
        .addScore('nerves',1.0)
        .addScore('speed',1.5)
        .addTextLines('default', [Text.gray('于群星间翩跹')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('随月相获得不同增益')])
        .addTextLines('alt,' [LEADING_SYMBOL, Text.gray('每20秒获得一次末影闪避')])
        .build())
        .texture('dlc:organ/stellar_pathway')
        .tag('kubejs:star')
        .tag('kubejs:player_tick_only')
        .displayName('星轨脉络');

    registerOrgan(new Organ('kubejs:rune_kidney')
        .addScore('metabolism', -0.5)
        .addScore('detoxification', -0.5)
        .addTextLines('default', [Text.gray('不那么狂乱的鸡尾酒.....吗？')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('每3秒有概率：增加所有效果时长、增加一项效果时长')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('提高所有效果等级、提高一项效果等级、移除一项效果')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('所有概率独立计算')])
        .build())
        .texture('dlc:organ/rune_kidney')
        .tag('kubejs:chaos')
        .tag('kubejs:player_tick_only')
        .displayName('符文肾脏');

    registerOrgan(new Organ('kubejs:wither_spine_claw')
        .addScore('withered',2.5)
        .addScore('nerves',1.5)
        .addScore('strength',1.5)
        .addScore('defense',1.0)
        .addTextLines('default', [Text.gray('凋亡的是灵魂，还是肉体？')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('击杀凋灵骷髅有70%的概率掉落头颅')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('不再受凋灵效果影响')])
        .build())
        .texture('dlc:organ/wither_spine_claw')
        .tag('kubejs:player_effect_only')
        .tag('kubejs:smelt')
        .tag('kubejs:loot_entity_only')
        .displayName('凋灵脊爪');

    registerOrgan(new Organ('kubejs:luminescent_sac_gland')
        .addScore('filtration', 1.5)
        .addScore('breath_capacity', 1.0)
        .addTextLines('default', [Text.gray('盈盈微光')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('受到攻击时，在周身产生萤火虫群，冷却15秒')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('夜晚为自己和周边队友回复生命')])
        .build())
        .texture('dlc:organ/luminescent_sac_gland')
        .tag('kubejs:nature')
        .tag('kubejs:magic')
        .tag('kubejs:player_tick')
        .tag('kubejs:bear_only')
        .displayName('萤囊腺体');

    registerOrgan(new Organ('kubejs:sarcoma_core')
        .addScore('health', -1.0)
        .addScore('metabolism', -0.5)
        .addScore('filtration', -1.0)
        .addTextLines('default', [Text.gray('搏动的核心吞噬着你的血肉')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('每击杀一个敌人，肉瘤增生：')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('根据胸腔内感染器官和肿瘤器官数量增加攻击力')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('每次扣除(10%*血量上限)血量(真实伤害)')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('叠加5次后，重置次数、产生爆炸')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('扣除自身(49%*血量上限)血量(真实伤害)并获得3秒无敌')])
        .build())
        .texture('dlc:organ/sarcoma_core')
        .tag('kubejs:infected')
        .tag('kubejs:loot_entity_only')
        .displayName('肉瘤核心');

    registerOrgan(new Organ('kubejs:bloodthorn_heart')
        .addScore('health', 1.0)
        .addScore('metabolism', 0.5)
        .addScore('filtration', 1.0)
        .addTextLines('default', [Text.gray('你以血驯养这丛荆棘')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('受伤时额外损失5点血量(真实伤害)并生成1根猩红尖刺攻击攻击者')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('使所有猩红尖刺附带吸血效果')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后增加鲜血法术强度')])
        .build())
        .texture('dlc:organ/bloodthorn_heart')
        .tag('kubejs:heart')
        .tag('kubejs:magic')
        .tag('kubejs:active_only')
        .tag('kubejs:bear_only')
        .tag('kubejs:damage_only')
        .displayName('血荆棘之心');
    
    registerOrgan(new Organ('kubejs:thundercloud_bone')
        .addScore('defense', 2.0)
        .addScore('strength', 2.0)
        .addScore('nerves', 1.5)
        .addTextLines('default', [Text.gray('风暴在骨髓中坍缩成蓝色电弧')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('雷暴天气时，雷电法术强度提升，攻击附带连锁闪电')])
        .build())
        .texture('dlc:organ/thundercloud_bone')
        .tag('kubejs:magic')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:damage_only')
        .displayName('雷云之骨');

    registerOrgan(new Organ('kubejs:nano_repair_core')
        .addScore('health',2.5)
        .addScore('digestion', 1.0)
        .addScore('defense', 2.0)
        .addScore('metabolism', 1.0)
        .addTextLines('default', [Text.gray('修补一切的纳米虫群')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('回复血量与手持物品耐久（主手和副手）')])
        .build())
        .texture('dlc:organ/nano_repair_core')
        .tag('kubejs:heart')
        .tag('kubejs:player_tick')
        .displayName('纳米修复核心');

    registerOrgan(new Organ('kubejs:phoenix_feather')
        .addScore('health', 5.0)
        .addScore('burning_point', -5)
        .addScore('freezing_point', -10)
        .addTextLines('default', [Text.gray('羽梢燃烧着永不坠落的黄昏')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('攻击对亡灵生物造成1.5倍伤害')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('死亡时触发不死图腾效果并获得一段时间部分属性提升，冷却120秒')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后增加烈焰法术强度')])
        .build())
        .texture('dlc:organ/phoenix_feather')
        .tag('kubejs:damage_only')
        .tag('kubejs:flame')
        .tag('kubejs:magic')
        .tag('kubejs:active_only')
        .displayName('凤凰之羽');

    registerOrgan(new Organ('kubejs:mimetic_gland')
        .addScore('health',0.5)
        .addScore('speed',1.5)
        .addTextLines('default', [Text.gray('潜行带师')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('获得真实隐身效果，攻击时失效')])
        .build())
        .texture('dlc:organ/mimetic_gland')
        .tag('kubejs:player_tick_only')
        .tag('kubejs:damage_only')
        .displayName('伪装腺体');
        
    registerOrgan(new Organ('kubejs:blaze_nucleus')
        .addScore('hydroallergenic', 3.0)
        .addScore('strength',-0.50)
        .addScore('buoyant',1)
        .addScore('burning_point', -8)
        .addScore('freezing_point', -15)
        .addTextLines('default', [Text.gray('fired on!')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('使用主动技能按键召唤3个小火球，向前方射击，冷却5s')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('免疫火焰伤害')])
        .build())
        .texture('dlc:organ/blaze_nucleus')
        .tag('kubejs:flame')
        .tag('kubejs:smelt')
        .tag('kubejs:key_pressed')
        .tag('kubejs:bear_only')
        .displayName('烈焰人核心');

    registerOrgan(new Organ('kubejs:jade_eye')
        .addScore('nerves',2)
        .addScore('qi_max', 10)
        .addScore('speed',2)
        .addTextLines('default', [Text.gray('常无欲，以观其妙；常有欲，以观其徼')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('战斗时半径20格内格生物发光')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('非战斗时，积累[悟道]，提升下次战斗的伤害与术法等级')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('战斗后清空[悟道]')])
        .build())
        .tag('kubejs:cultivate')
        .tag('kubejs:damage_only')
        .tag('kubejs:player_tick_only')
        .texture('dlc:organ/jade_eye')
        .displayName('青玉之瞳');    
        
    registerOrgan(new Organ('kubejs:darksteel_spine')
        .addScore('defense', 6)
        .addScore('nerves',2)
        .addScore('qi_max', 10)
        .addScore('speed',-4)
        .addTextLines('default', [Text.gray('致虚极，守静笃')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('不再受负面效果影响')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('积累的[悟道]提供减伤')])
        .build())
        .tag('kubejs:player_effect_only')
        .tag('kubejs:bear_only')
        .tag('kubejs:cultivate')
        .texture('dlc:organ/darksteel_spine')
        .displayName('玄铁脊柱');

    registerOrgan(new Organ('kubejs:flower_of_heart')
        .addScore('strength',3.0)
        .addScore('health',1.0)
        .addTextLines('default', [Text.gray('彼时，落英萦绕锋尘')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('取消被攻击目标无敌时间')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('攻击时召唤8瓣花瓣进行协同攻击，冷却2.5秒')])
        .addTextLines('alt', [LEADING_SYMBOL, Text.gray('若对称位置存在花之心，花瓣数提升至16')])
        .addTextLines('ctrl', [LEADING_SYMBOL, Text.gray('激活后根据自然器官数量提供攻击力')])
        .build())
        .tag('kubejs:damage_only')
        .tag('kubejs:active_only')
        .tag('kubejs:nature')
        .texture('dlc:organ/flower_of_heart')
        .displayName('心之花');
});