ServerEvents.tags('item',event=>{
	event.add('kubejs:flame',[
		'kubejs:burning_heart',
		'kubejs:furnace_core',
		'kubejs:blaze_pressurizer',
		'kubejs:embers_liver',
		'kubejs:fire_dragon_bead',
		'kubejs:sunbird_crystals',
		'kubejs:revolution_relay',
		'kubejs:revolution_cable',
		'kubejs:revolution_steam_engine',
		'kubejs:revolution_bell',
		'kubejs:immortal_volcanic_rock',
		'kubejs:frenzy_blast_furance',
		'kubejs:vulcan_furnace',
		'kubejs:lava_life_cycle_system',
		'kubejs:love_between_lava_and_ice',
		'kubejs:redstone_furnace'
	])
	event.add('kubejs:ice',[
		'kubejs:freezing_intestine',
		'kubejs:ice_dragon_bead',
		'kubejs:magic_vision',
		'kubejs:magic_muscle',
		'kubejs:magic_spine',
		'kubejs:magic_hippocampus',
		'kubejs:love_between_lava_and_ice'
	])
	event.add('kubejs:sculk',[
		'kubejs:warden_core',
		'kubejs:warden_rib',
		'kubejs:warden_muscle',
		'kubejs:sculk_soul',
		'kubejs:sculk_pieces'
	])
	event.add('kubejs:color',['kubejs:color_palette'])
})
