ServerEvents.tags('item',event=>{
	event.add('kubejs:flame',[
		'kubejs:burning_heart',
		'kubejs:furnace_core',
		'kubejs:blaze_pressurizer',
		'kubejs:embers_liver',
		'kubejs:fire_dragon_bead',
		'kubejs:sunbird_crystals',
		'kubejs:revolution_relay',
		'kubejs:revolution_cable',
		'kubejs:revolution_steam_engine',
		'kubejs:revolution_bell',
		'kubejs:immortal_volcanic_rock',
		'kubejs:frenzy_blast_furance',
		'kubejs:vulcan_furnace',
		'kubejs:lava_life_cycle_system',
		'kubejs:love_between_lava_and_ice',
		'kubejs:redstone_furnace'
	])
	event.add('kubejs:ice',[
		'kubejs:freezing_intestine',
		'kubejs:ice_dragon_bead',
		'kubejs:magic_vision',
		'kubejs:magic_muscle',
		'kubejs:magic_spine',
		'kubejs:magic_hippocampus',
		'kubejs:love_between_lava_and_ice'
	])
	event.add('kubejs:sculk',[
		'kubejs:warden_core',
		'kubejs:warden_rib',
		'kubejs:warden_muscle',
		'kubejs:sculk_soul',
		'kubejs:sculk_pieces'
	])
	event.add('minecraft:planks',['kubejs:lightning_planks'])

	event.add('forge:ores',[
			'unusualprehistory:plant_fossil', 
			'unusualprehistory:stone_opal_ore', 
			'unusualprehistory:stone_fossil', 
			'iceandfire:silver_ore', 
			'unusualprehistory:stone_amber_ore', 
			'unusualprehistory:deepslate_fossil',
			'unusualprehistory:deepslate_opal_ore', 
			'minecraft:amethyst_block', 
			'minecraft:magma_block',
			'unusualprehistory:deepslate_opal_ore',
			'unusualprehistory:deepslate_plant_fossil',
			'irons_spellbooks:arcane_debris'
		])
	
	event.add('kubejs:nature',['kubejs:flower_heart']);
	event.add('kubejs:chaos',['kubejs:viviparous_crinoidea']);
	event.add('kubejs:hogskin',['cold_sweat:hoglin_hide','irons_spellbooks:hogskin'])
	/*
	for (let [key, value] of Object.entries(global.TYPE_MAP)){
		event.add(key,['kubejs:chaos_tumor'])
	};
	*/
})

