StartupEvents.registry('minecraft:block',event=>{
    event.create('kubejs:lightning_wood','basic')
        .textureAll('dlc:block/lightning_wood')
        .texture('north','dlc:block/lightning_wood')
        .texture('south','dlc:block/lightning_wood')
        .texture('west','dlc:block/lightning_wood')
        .texture('east','dlc:block/lightning_wood')
        .texture('up', 'dlc:block/lightning_wood_top')
        .texture('down', 'dlc:block/lightning_wood_top')
        .material('wood')
        .woodSoundType()
        .displayName('雷击木')

    event.create('kubejs:lightning_planks','basic')
        .textureAll('dlc:block/lightning_planks')
        .material('wood')
        .woodSoundType()
        .displayName('雷击木板')
})